# Dependencies
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments

# Premalinks
permalink: pretty

future: TRUE

source: _source/
#baseurl: http://www.cs.rpi.edu/~acm-w/

title: RPI ACM-W
#tagline: 'RPI's group for Women in Computing'
# description: 'RPI's Chapter of the ACM-W'

# author:
#   name: 'Elsa Gonsiorowski'
#   url: http://www.gonsie.com

# # number of posts that appear on a page
# paginate: 5

# # Sidebar Vars
# #version: 1.0
# github:
#   repo: https://github.com/RPI-ACM-W

# # Exclude Files
# exclude: ['README.md']
