# Dependencies
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments

# Premalinks
permalink: none

future: TRUE

source: _source/

## SEMESTER ORDERING
## change this to update the Events page
category-list: ["fall 2015", "summer 2015", "spring 2015"]

## Use this for development with blank --baseurl= flag
## `bundle exec jekyll serve -w --baseurl=`
#baseurl: http://0.0.0.0:4000/

## Use this for deployment
baseurl: http://acmw.rpi.edu

title: RPI ACM-W
tagline: "RPI's group for Women in Computing"
# description: 'RPI's Chapter of the ACM-W'

# author:
#   name: 'Elsa Gonsiorowski'
#   url: http://www.gonsie.com

# # number of posts that appear on a page
# paginate: 5

# # Sidebar Vars
# #version: 1.0
github:
  repo: https://github.com/RPI-ACM-W/rpi-acm-w.github.io

# Exclude Files
exclude: ['_posts/template.md']
